package types

type MetaDataPayload struct {
	DeviceType             string                 `json:"deviceType"`
	DeviceID               string                 `json:"deviceId"`
	AppSessionID           string                 `json:"appSessionId"`
	OsVersion              string                 `json:"osVersion"`
	Display                Display                `json:"display"`
	SensorsMetadata        SensorsMetadata        `json:"sensorsMetadata"`
	IdentificationMetadata IdentificationMetadata `json:"identificationMetadata"`
	IoMetadata             IoMetadata             `json:"ioMetadata"`
	BaseTimestamp          int64                  `json:"baseTimestamp"`
	EpochTimeInMillis      int64                  `json:"epochTimeInMillis"`
}
type Display struct {
	Ops              int         `json:"ops"`
	WebGl            string      `json:"webGl"`
	DevicePixelRatio int         `json:"devicePixelRatio"`
	ScreenWidth      int         `json:"screenWidth"`
	ScreenHeight     int         `json:"screenHeight"`
	AvailWidth       int         `json:"availWidth"`
	AvailHeight      int         `json:"availHeight"`
	Width            int         `json:"width"`
	Height           int         `json:"height"`
	ColorDepth       int         `json:"colorDepth"`
	PixelDepth       int         `json:"pixelDepth"`
	AvailLeft        int         `json:"availLeft"`
	AvailTop         int         `json:"availTop"`
	Onchange         interface{} `json:"onchange"`
	IsExtended       bool        `json:"isExtended"`
}
type SensorsMetadata struct {
	DedvceLightSupported bool `json:"DEDVCE_LIGHT_SUPPORTED"`
	IsTouchDevice        bool `json:"IS_TOUCH_DEVICE"`
	ProximitySupported   bool `json:"PROXIMITY_SUPPORTED"`
}
type IdentificationMetadata struct {
	OsName                                           string `json:"OS_NAME"`
	OsVersion                                        string `json:"OS_VERSION"`
	DeviceModel                                      string `json:"DEVICE_MODEL"`
	DeviceVendor                                     string `json:"DEVICE_VENDOR"`
	BrowserEngineName                                string `json:"BROWSER_ENGINE_NAME"`
	BrowserEngineVersion                             string `json:"BROWSER_ENGINE_VERSION"`
	CPUArchitecture                                  string `json:"CPU_ARCHITECTURE"`
	NavigatorVendor                                  string `json:"NAVIGATOR_VENDOR"`
	NavigatorPluginsLength                           int    `json:"NAVIGATOR_PLUGINS_LENGTH"`
	NavigatorMimeTypesLength                         int    `json:"NAVIGATOR_MIME_TYPES_LENGTH"`
	NavigatorLanguage                                string `json:"NAVIGATOR_LANGUAGE"`
	NAVIGATORLANGUAGES0                              string `json:"NAVIGATOR_LANGUAGES.0"`
	NAVIGATORLANGUAGES1                              string `json:"NAVIGATOR_LANGUAGES.1"`
	NAVIGATORLANGUAGES2                              string `json:"NAVIGATOR_LANGUAGES.2"`
	NavigatorWebDriver                               bool   `json:"NAVIGATOR_WEB_DRIVER"`
	NavigatorHardwareConcurrency                     int    `json:"NAVIGATOR_HARDWARE_CONCURRENCY"`
	NavigatorVibrate                                 bool   `json:"NAVIGATOR_VIBRATE"`
	PushNotificationsSupported                       bool   `json:"PUSH_NOTIFICATIONS_SUPPORTED"`
	NavigatorAppCodeName                             string `json:"NAVIGATOR_APP_CODE_NAME"`
	NavigatorAppName                                 string `json:"NAVIGATOR_APP_NAME"`
	NavigatorAppVersion                              string `json:"NAVIGATOR_APP_VERSION"`
	NavigatorOnLine                                  bool   `json:"NAVIGATOR_ON_LINE"`
	NavigatorPlatform                                string `json:"NAVIGATOR_PLATFORM"`
	NavigatorProduct                                 string `json:"NAVIGATOR_PRODUCT"`
	NavigatorUserAgent                               string `json:"NAVIGATOR_USER_AGENT"`
	NavigatorDeviceMemory                            int    `json:"NAVIGATOR_DEVICE_MEMORY"`
	NavigatorConnectionRtt                           int    `json:"NAVIGATOR_CONNECTION_RTT"`
	AmbientLight                                     bool   `json:"ambient_light"`
	ApplicationCache                                 bool   `json:"application_cache"`
	AudioL                                           bool   `json:"audio"`
	AudioOgg                                         string `json:"audio.ogg"`
	AudioMp3                                         string `json:"audio.mp3"`
	AudioOpus                                        string `json:"audio.opus"`
	AudioWav                                         string `json:"audio.wav"`
	AudioM4A                                         string `json:"audio.m4a"`
	BatteryAPI                                       bool   `json:"battery_api"`
	BlobConstructor                                  bool   `json:"blob_constructor"`
	ContextMenu                                      bool   `json:"context_menu"`
	Cors                                             bool   `json:"cors"`
	CustomElements                                   bool   `json:"custom_elements"`
	CustomProtocolHandler                            bool   `json:"custom_protocol_handler"`
	CustomEvent                                      bool   `json:"custom_event"`
	Dart                                             bool   `json:"dart"`
	DataView                                         bool   `json:"data_view"`
	EventListener                                    bool   `json:"event_listener"`
	ForceTouch                                       bool   `json:"force_touch"`
	FullScreen                                       bool   `json:"full_screen"`
	GamePads                                         bool   `json:"game_pads"`
	GeoLocation                                      bool   `json:"geo_location"`
	Ie8Compat                                        bool   `json:"ie8compat"`
	Internationalization                             bool   `json:"internationalization"`
	JSON                                             bool   `json:"json"`
	Ligatures                                        bool   `json:"ligatures"`
	MediaSource                                      bool   `json:"media_source"`
	MessageChannel                                   bool   `json:"message_channel"`
	Notification                                     bool   `json:"notification"`
	PageVisibility                                   bool   `json:"page_visibility"`
	Performance                                      bool   `json:"performance"`
	PointerEvents                                    bool   `json:"pointer_events"`
	PointerLock                                      bool   `json:"pointer_lock"`
	QuerySelector                                    bool   `json:"query_selector"`
	QuotaManagement                                  bool   `json:"quota_management"`
	RequestAnimationFrame                            bool   `json:"request_animation_frame"`
	ServiceWorker                                    bool   `json:"service_worker"`
	TouchEvents                                      bool   `json:"touch_events"`
	TypedArrays                                      bool   `json:"typed_arrays"`
	Vibrate                                          bool   `json:"vibrate"`
	VideoL                                           bool   `json:"video"`
	VideoOgg                                         string `json:"video.ogg"`
	VideoH264                                        string `json:"video.h264"`
	VideoH265                                        string `json:"video.h265"`
	VideoWebm                                        string `json:"video.webm"`
	VideoVp9                                         string `json:"video.vp9"`
	VideoHls                                         string `json:"video.hls"`
	VideoAv1                                         string `json:"video.av1"`
	WebGl                                            bool   `json:"web_gl"`
	WebSockets                                       bool   `json:"web_sockets"`
	XDomainRequest                                   bool   `json:"x_domain_request"`
	Matchmedia                                       bool   `json:"matchmedia"`
	JSCHALLENGEStatus                                string `json:"JS_CHALLENGE.status"`
	JSCHALLENGESessionID                             string `json:"JS_CHALLENGE.sessionId"`
	IsWebgl                                          bool   `json:"IS_WEBGL"`
	Webglvendorandrenderer                           string `json:"WEBGLVENDORANDRENDERER"`
	IsWebgl2                                         bool   `json:"IS_WEBGL2"`
	Webgl2Vendorandrenderer                          string `json:"WEBGL2VENDORANDRENDERER"`
	Hasliedlanguages                                 bool   `json:"HASLIEDLANGUAGES"`
	Hasliedresolution                                bool   `json:"HASLIEDRESOLUTION"`
	Hasliedos                                        bool   `json:"HASLIEDOS"`
	Hasliedbrowser                                   bool   `json:"HASLIEDBROWSER"`
	IsIncognito                                      bool   `json:"IS_INCOGNITO"`
	IsPrivateMode                                    bool   `json:"IS_PRIVATE_MODE"`
	IsWebGlstatus                                    int    `json:"IS_WEB_GLSTATUS"`
	HEADLESSSelenium                                 string `json:"HEADLESS.selenium"`
	HEADLESSPhantomjsPhantom                         string `json:"HEADLESS.phantomjs._phantom"`
	HEADLESSPhantomjsPhantomas                       string `json:"HEADLESS.phantomjs.__phantomas"`
	HEADLESSPhantomjsCallPhantom                     string `json:"HEADLESS.phantomjs.callPhantom"`
	HEADLESSNodejsBuffer                             string `json:"HEADLESS.nodejs.Buffer"`
	HEADLESSCouchjsEmit                              string `json:"HEADLESS.couchjs.emit"`
	HEADLESSRhinoSpawn                               string `json:"HEADLESS.rhino.spawn"`
	HEADLESSChromiumDomAutomationController          string `json:"HEADLESS.chromium.domAutomationController"`
	HEADLESSChromiumDomAutomation                    string `json:"HEADLESS.chromium.domAutomation"`
	HEADLESSOuterWidth                               int    `json:"HEADLESS.outerWidth"`
	HEADLESSOuterHeight                              int    `json:"HEADLESS.outerHeight"`
	HEADLESSHeadlessChrome                           bool   `json:"HEADLESS.headless_chrome"`
	HEADLESSNavigatorWebdriverPresent                bool   `json:"HEADLESS.navigator.webdriver_present"`
	HEADLESSWindowChromeMissing                      bool   `json:"HEADLESS.window.chrome_missing"`
	HEADLESSPermissionsAPIOverriden                  bool   `json:"HEADLESS.permissions_api_overriden"`
	HEADLESSNavigatorPluginsEmpty                    bool   `json:"HEADLESS.navigator.plugins_empty"`
	HEADLESSNavigatorLanguagesBlank                  bool   `json:"HEADLESS.navigator.languages_blank"`
	HEADLESSConsistentPluginsPrototype               bool   `json:"HEADLESS.consistent_plugins_prototype"`
	HEADLESSConsistentMimetypesPrototype             bool   `json:"HEADLESS.consistent_mimetypes_prototype"`
	HEADLESSIframeWindowHeadlessChrome               bool   `json:"HEADLESS.iframe_window.headless_chrome"`
	HEADLESSIframeWindowNavigatorWebdriverPresent    bool   `json:"HEADLESS.iframe_window.navigator.webdriver_present"`
	HEADLESSIframeWindowWindowChromeMissing          bool   `json:"HEADLESS.iframe_window.window.chrome_missing"`
	HEADLESSIframeWindowPermissionsAPIOverriden      bool   `json:"HEADLESS.iframe_window.permissions_api_overriden"`
	HEADLESSIframeWindowNavigatorPluginsEmpty        bool   `json:"HEADLESS.iframe_window.navigator.plugins_empty"`
	HEADLESSIframeWindowNavigatorLanguagesBlank      bool   `json:"HEADLESS.iframe_window.navigator.languages_blank"`
	HEADLESSIframeWindowConsistentPluginsPrototype   bool   `json:"HEADLESS.iframe_window.consistent_plugins_prototype"`
	HEADLESSIframeWindowConsistentMimetypesPrototype bool   `json:"HEADLESS.iframe_window.consistent_mimetypes_prototype"`
	HEADLESSIframeWindowPermissionsAPI               bool   `json:"HEADLESS.iframe_window.permissions_api"`
	STEALTHSrcdocThrowsError                         bool   `json:"STEALTH.srcdoc_throws_error"`
	STEALTHSrcdocTriggersWindowProxy                 bool   `json:"STEALTH.srcdoc_triggers_window_proxy"`
	STEALTHIndexChromeTooHigh                        bool   `json:"STEALTH.index_chrome_too_high"`
	STEALTHChromeRuntimeFunctionsInvalid             bool   `json:"STEALTH.chrome_runtime_functions_invalid"`
	STEALTHFunctionPrototypeToStringInvalidTypeError bool   `json:"STEALTH.Function_prototype_toString_invalid_typeError"`
	RefLink                                          string `json:"REF_LINK"`
	PLUGINSLength                                    int    `json:"PLUGINS.length"`
	PLUGINSDetails0Length                            int    `json:"PLUGINS.details.0.length"`
	PLUGINSDetails0Name                              string `json:"PLUGINS.details.0.name"`
	PLUGINSDetails0Filename                          string `json:"PLUGINS.details.0.filename"`
	PLUGINSDetails1Length                            int    `json:"PLUGINS.details.1.length"`
	PLUGINSDetails1Name                              string `json:"PLUGINS.details.1.name"`
	PLUGINSDetails1Filename                          string `json:"PLUGINS.details.1.filename"`
	PLUGINSDetails2Length                            int    `json:"PLUGINS.details.2.length"`
	PLUGINSDetails2Name                              string `json:"PLUGINS.details.2.name"`
	PLUGINSDetails2Filename                          string `json:"PLUGINS.details.2.filename"`
	PLUGINSDetails3Length                            int    `json:"PLUGINS.details.3.length"`
	PLUGINSDetails3Name                              string `json:"PLUGINS.details.3.name"`
	PLUGINSDetails3Filename                          string `json:"PLUGINS.details.3.filename"`
	PLUGINSDetails4Length                            int    `json:"PLUGINS.details.4.length"`
	PLUGINSDetails4Name                              string `json:"PLUGINS.details.4.name"`
	PLUGINSDetails4Filename                          string `json:"PLUGINS.details.4.filename"`
	Audio                                            int    `json:"AUDIO"`
	Video                                            int    `json:"VIDEO"`
	VideoInputDevices                                string `json:"VIDEO_INPUT_DEVICES"`
	AudioInputDevices                                string `json:"AUDIO_INPUT_DEVICES"`
	AudioOutputDevices                               string `json:"AUDIO_OUTPUT_DEVICES"`
	MediaCodecMp4Avc1                                string `json:"MEDIA_CODEC_MP4_AVC1"`
	MediaCodecXM4A                                   string `json:"MEDIA_CODEC_X_M4A"`
	MediaCodecAac                                    string `json:"MEDIA_CODEC_AAC"`
	MemoryHeapSizeLimit                              int64  `json:"MEMORY_HEAP_SIZE_LIMIT"`
	MemoryTotalHeapSize                              int    `json:"MEMORY_TOTAL_HEAP_SIZE"`
	MemoryUsedHeapSize                               int    `json:"MEMORY_USED_HEAP_SIZE"`
	IsAcceptCookies                                  bool   `json:"IS_ACCEPT_COOKIES"`
	SeleniumInDocument                               bool   `json:"selenium_in_document"`
	SeleniumInWindow                                 bool   `json:"selenium_in_window"`
	SeleniumInNavigator                              bool   `json:"selenium_in_navigator"`
	SeleniumSequentum                                bool   `json:"selenium_sequentum"`
	DocumentElementSelenium                          string `json:"DOCUMENT_ELEMENT_SELENIUM"`
	DocumentElementWebdriver                         string `json:"DOCUMENT_ELEMENT_WEBDRIVER"`
	DocumentElementDriver                            string `json:"DOCUMENT_ELEMENT_DRIVER"`
	WindowHTMLWebdriver                              bool   `json:"window_html_webdriver"`
	WindowGeb                                        bool   `json:"window_geb"`
	WindowAwesomium                                  bool   `json:"window_awesomium"`
	WindowRunPerfTest                                bool   `json:"window_RunPerfTest"`
	WindowFmgetTargets                               bool   `json:"window_fmget_targets"`
	HasTrustToken                                    bool   `json:"hasTrustToken"`
	TrustTokenOperationError                         bool   `json:"trustTokenOperationError"`
	SetTrustToken                                    bool   `json:"setTrustToken"`
	TrustToken                                       bool   `json:"trustToken"`
	LocalStorageLength                               int    `json:"localStorage.length"`
	SessionStorageLength                             int    `json:"sessionStorage.length"`
	WebRtcEnabled                                    bool   `json:"WEB_RTC_ENABLED"`
	MQSCREENMatches                                  bool   `json:"MQ_SCREEN.matches"`
	MQSCREENMedia                                    string `json:"MQ_SCREEN.media"`
	IframeChrome                                     string `json:"IFRAME_CHROME"`
	IframeWidth                                      int    `json:"IFRAME_WIDTH"`
	IframeHeight                                     int    `json:"IFRAME_HEIGHT"`
	NotificationPermission                           string `json:"NOTIFICATION_PERMISSION"`
	HasChromeApp                                     bool   `json:"HAS_CHROME_APP"`
	HasChromeCsi                                     bool   `json:"HAS_CHROME_CSI"`
	HasChromeLoadtimes                               bool   `json:"HAS_CHROME_LOADTIMES"`
	HasChromeRuntime                                 bool   `json:"HAS_CHROME_RUNTIME"`
	ChromiumMath                                     bool   `json:"CHROMIUM_MATH"`
	ChromePropertyDescriptorApp                      string `json:"CHROME_PROPERTY_DESCRIPTOR_APP"`
	ChromePropertyDescriptorCsi                      string `json:"CHROME_PROPERTY_DESCRIPTOR_CSI"`
	ChromePropertyDescriptorLoadtimes                string `json:"CHROME_PROPERTY_DESCRIPTOR_LOADTIMES"`
	ChromePropertyDescriptorRuntime                  string `json:"CHROME_PROPERTY_DESCRIPTOR_RUNTIME"`
	NavigatorPropertyDescriptorLanguages             string `json:"NAVIGATOR_PROPERTY_DESCRIPTOR_LANGUAGES"`
	NavigatorPropertyDescriptorHardwareconcurrency   string `json:"NAVIGATOR_PROPERTY_DESCRIPTOR_HARDWARECONCURRENCY"`
	ScreenPropertyDescriptorWidth                    string `json:"SCREEN_PROPERTY_DESCRIPTOR_WIDTH"`
	ScreenPropertyDescriptorHeight                   string `json:"SCREEN_PROPERTY_DESCRIPTOR_HEIGHT"`
	NavigatorPropertyDescriptorWebdriver             string `json:"NAVIGATOR_PROPERTY_DESCRIPTOR_WEBDRIVER"`
	WindowPropertyDescriptorOuterwidth               string `json:"WINDOW_PROPERTY_DESCRIPTOR_OUTERWIDTH"`
	WindowPropertyDescriptorOuterheight              string `json:"WINDOW_PROPERTY_DESCRIPTOR_OUTERHEIGHT"`
}
type IoMetadata struct {
	BlutoothSupported            bool        `json:"BLUTOOTH_SUPPORTED"`
	HasSpeakers                  bool        `json:"HAS_SPEAKERS"`
	HasMicrophone                bool        `json:"HAS_MICROPHONE"`
	BatterySupported             bool        `json:"BATTERY_SUPPORTED"`
	BatteryLevel                 int         `json:"BATTERY_LEVEL"`
	BatteryCharging              bool        `json:"BATTERY_CHARGING"`
	BatteryChargingTime          int         `json:"BATTERY_CHARGING_TIME"`
	BatteryDischargingTime       interface{} `json:"BATTERY_DISCHARGING_TIME"`
	GpsSupported                 bool        `json:"GPS_SUPPORTED"`
	IsMobile                     bool        `json:"IS_MOBILE"`
	HasTouch                     bool        `json:"HAS_TOUCH"`
	PERMISSIONSAccelerometer     string      `json:"PERMISSIONS.accelerometer"`
	PERMISSIONSBackgroundSync    string      `json:"PERMISSIONS.background-sync"`
	PERMISSIONSCamera            string      `json:"PERMISSIONS.camera"`
	PERMISSIONSClipboardRead     string      `json:"PERMISSIONS.clipboard-read"`
	PERMISSIONSClipboardWrite    string      `json:"PERMISSIONS.clipboard-write"`
	PERMISSIONSGeolocation       string      `json:"PERMISSIONS.geolocation"`
	PERMISSIONSGyroscope         string      `json:"PERMISSIONS.gyroscope"`
	PERMISSIONSMagnetometer      string      `json:"PERMISSIONS.magnetometer"`
	PERMISSIONSMicrophone        string      `json:"PERMISSIONS.microphone"`
	PERMISSIONSMidi              string      `json:"PERMISSIONS.midi"`
	PERMISSIONSNotifications     string      `json:"PERMISSIONS.notifications"`
	PERMISSIONSPaymentHandler    string      `json:"PERMISSIONS.payment-handler"`
	PERMISSIONSPersistentStorage string      `json:"PERMISSIONS.persistent-storage"`
	PrefersColorScheme           string      `json:"PREFERS_COLOR_SCHEME"`
}
